services:
  mychat:
    container_name: mychat_app
    image: mychat
    build:
      context: .
      dockerfile: python.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ".:/mychat"
    environment:
      - DJANGO_SETTINGS_MODULE=mychat.settings.base
    tty: true
    restart: unless-stopped

  nginx:
    image: nginx:1.25.0
    container_name: mychat_nginx
    ports:
      - "80:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./mychat/static:/mychat/mychat/static"
      - "./mychat/media:/mychat/mychat/media"
      - "./.data/logs/nginx:/var/log/nginx"
    restart: unless-stopped
